version: 2.1
orbs:
  artifact-management: avvo/artifact-management@0.0.3
jobs:
  test:
    docker:
      - image: circleci/ruby:2.6
    steps:
      - checkout
      - run: gem install bundler --version=1.17.3
      - run: bundle
      - run: bundle exec rake test
  build:
    docker:
      - image: circleci/ruby:2.6
    steps:
      - checkout
      - artifact-management/gem-build-and-push
workflows:
  version: 2.1
  build-workflow:
    jobs:
      - test:
          context: org-global
      - build:
          context: org-global
          filters:
            tags:
              only: /^v[0-9]+\.[0-9]+\.[0-9]+.*/
            branches:
              ignore: /.*/
